config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root 'homes#top'
  get "/home/about" => "homes#about"
  get '/search' => 'search#search'

  resources :users, only: [:show, :index, :edit, :update]
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  resources :users do
    get :following_user, on: :member
    get :follower_user, on: :member
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
  end

  def destroy
    @comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], url: book_book_comments_path(book) ) do |f| %>
  <%= f.text_area :comment, size:"90x5", rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
<% book_comments.each do |book_comment| %>
  <tr>
　  <td>
　　  <%= link_to user_path(book_comment.user) do %>
      <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %><br>
      <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
    <td><%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/book_comments/create.js.erb
$(".comments_area").html("<%= j(render 'book_comments/index', { book_comments: @book.book_comments }) %>");
$(".comments_count").html("コメント件数：<%= @book.book_comments.count %>");
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$(".comments_area").html("<%= j(render 'book_comments/index', { book_comments: @comment.book.book_comments }) %>");
$(".comments_count").html("コメント件数：<%= @comment.book.book_comments.count %>");
$("textarea").val('')